name = "jenosize"
type = "javascript"
# webpack_config = "webpack.config.js"

account_id = "a2066c72b45c4f070d95a9af1c3d56a7"
workers_dev = true
route = ""
zone_id = ""

# [build]
# command = "npm install && npm run build"
# [build.upload]
# format = "service-worker"